In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

### 데이터 불러오기

In [ ]:
df_raw = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/KOSMI/heart.csv') #Set Dir

In [ ]:
df = df_raw.copy()

In [ ]:
df.head(20)

    age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0    63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1    37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2    41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3    56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4    57    0   0       120   354    0  ...      1      0.6      2   0     2       1
5    57    1   0       140   192    0  ...      0      0.4      1   0     1       1
6    56    0   1       140   294    0  ...      0      1.3      1   0     2       1
7    44    1   1       120   263    0  ...      0      0.0      2   0     3       1
8    52    1   2       172   199    1  ...      0      0.5      2   0     3       1
9    57    1   2       150   168    0  ...      0      1.6      2   0     2       1
10   54    1   0       140   239    0  ...      0      1.2      2   0     2       1
11   48    0   2       130   275    0  ...      0      0.2      2   0     2       1
12   49    1   1       130   266    0  ...      0      0.6      2   0     2       1
13   64    1   3       110   211    0  ...      1      1.8      1   0     2       1
14   58    0   3       150   283    1  ...      0      1.0      2   0     2       1
15   50    0   2       120   219    0  ...      0      1.6      1   0     2       1
16   58    0   2       120   340    0  ...      0      0.0      2   0     2       1
17   66    0   3       150   226    0  ...      0      2.6      0   0     2       1
18   43    1   0       150   247    0  ...      0      1.5      2   0     2       1
19   69    0   3       140   239    0  ...      0      1.8      2   2     2       1

[20 rows x 14 columns]

### 결측치 확인

In [ ]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### 정규화

In [ ]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
standardScaler.fit(df[['age']])
df[['age']] = standardScaler.transform(df[['age']])

standardScaler.fit(df[['trestbps']])
df[['trestbps']] = standardScaler.transform(df[['trestbps']])

standardScaler.fit(df[['chol']])
df[['chol']] = standardScaler.transform(df[['chol']])

standardScaler.fit(df[['thalach']])
df[['thalach']] = standardScaler.transform(df[['thalach']])

standardScaler.fit(df[['oldpeak']])
df[['oldpeak']] = standardScaler.transform(df[['oldpeak']])

### 원핫인코딩

In [ ]:
pd.get_dummies(df['sex'])
pd.get_dummies(df['cp'])
pd.get_dummies(df['fbs'])
pd.get_dummies(df['restecg'])
pd.get_dummies(df['exang'])
pd.get_dummies(df['slope'])
pd.get_dummies(df['ca'])
pd.get_dummies(df['thal'])

     0  1  2  3
0    0  1  0  0
1    0  0  1  0
2    0  0  1  0
3    0  0  1  0
4    0  0  1  0
..  .. .. .. ..
298  0  0  0  1
299  0  0  0  1
300  0  0  0  1
301  0  0  0  1
302  0  0  1  0

[303 rows x 4 columns]

### 타겟변수 설정

In [ ]:
target_col = 'target'
target = df[target_col]

### features 변수들 설정

In [ ]:
features = df[['age','sex','cp', 'trestbps','chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']]

### test/train 셋 분리

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size = 0.3, random_state=3
)

### 의사결정트리

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
DTree = DecisionTreeClassifier(random_state = 0)
DTree.fit(X_train, y_train)
print(DTree.score(X_test, y_test))

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

y_pred = DTree.predict(X_test)

print(classification_report(y_test,y_pred))

print("Precision : ", precision_score(y_test, y_pred,average='macro'))
print("Recall : ", recall_score(y_test, y_pred,average='macro'))
print("F1-Score : ", f1_score(y_test, y_pred,average='macro'))
print("Accuracy : ", accuracy_score(y_test, y_pred))

0.7472527472527473
              precision    recall  f1-score   support

           0       0.67      0.76      0.72        38
           1       0.81      0.74      0.77        53

    accuracy                           0.75        91
   macro avg       0.74      0.75      0.74        91
weighted avg       0.75      0.75      0.75        91

Precision :  0.7434593023255813
Recall :  0.7495034756703078
F1-Score :  0.7441633052194108
Accuracy :  0.7472527472527473

### 랜덤포레스트

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=10)
RF.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

y_pred = RF.predict(X_test)

print("Precision : ", precision_score(y_test, y_pred,average='macro'))
print("Recall : ", recall_score(y_test, y_pred,average='macro'))
print("F1-Score : ", f1_score(y_test, y_pred,average='macro'))
print("Accuracy : ", accuracy_score(y_test, y_pred))

Precision :  0.8475232198142415
Recall :  0.8344091360476664
F1-Score :  0.8391414141414141
Accuracy :  0.8461538461538461

### GBM(Gradient Boosting Machine)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gb = GradientBoostingClassifier(random_state=0)
gb.fit(X_train, y_train)


y_pred = gb.predict(X_test)
print(classification_report(y_test,y_pred))

print("Precision : ", precision_score(y_test, y_pred,average='macro'))
print("Recall : ", recall_score(y_test, y_pred,average='macro'))
print("F1-Score : ", f1_score(y_test, y_pred,average='macro'))
print("Accuracy : ", accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.74      0.76        38
           1       0.82      0.85      0.83        53

    accuracy                           0.80        91
   macro avg       0.80      0.79      0.80        91
weighted avg       0.80      0.80      0.80        91

Precision :  0.797979797979798
Recall :  0.7929493545183715
F1-Score :  0.795045045045045
Accuracy :  0.8021978021978022

### XGBoost

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print(classification_report(y_test,y_pred))
print("Precision : ", precision_score(y_test, y_pred,average='macro'))
print("Recall : ", recall_score(y_test, y_pred,average='macro'))
print("F1-Score : ", f1_score(y_test, y_pred,average='macro'))
print("Accuracy : ", accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.76      0.81        38
           1       0.84      0.91      0.87        53

    accuracy                           0.85        91
   macro avg       0.85      0.83      0.84        91
weighted avg       0.85      0.85      0.84        91

Precision :  0.8475232198142415
Recall :  0.8344091360476664
F1-Score :  0.8391414141414141
Accuracy :  0.8461538461538461